arcanas = [
    {"id": 1, "name": "Fool"},
    {"id": 2, "name": "Magician"},
    {"id": 3, "name": "Priestess"},
    {"id": 4, "name": "Empress"},
    {"id": 5, "name": "Emperor"},
    {"id": 6, "name": "Hierophant"},
    {"id": 7, "name": "Lovers"},
    {"id": 8, "name": "Chariot"},
    {"id": 9, "name": "Justice"},
    {"id": 10, "name": "Hermit"},
    {"id": 11, "name": "Fortune"},
    {"id": 12, "name": "Strength"},
    {"id": 13, "name": "Hanged Man"},
    {"id": 14, "name": "Death"},
    {"id": 15, "name": "Temperance"},
    {"id": 16, "name": "Devil"},
    {"id": 17, "name": "Tower"},
    {"id": 18, "name": "Star"},
    {"id": 19, "name": "Moon"},
    {"id": 20, "name": "Sun"},
    {"id": 21, "name": "Judgement"},
    {"id": 22, "name": "Aeon"},
    {"id": 23, "name": "World"}
]

wildcards = [
    {"id": 1, "name": "Makoto Yuki", "image": "makoto_yuki_wildcard.png", "initial_persona_id": "Orpheus"},
    {"id": 2, "name": "Yu Narukami", "image": "yu_narukami_wildcard.png", "initial_persona_id": "Izanagi"},
    {"id": 3, "name": "Ren Amamiya", "image": "ren_amamiya_wildcard.png", "initial_persona_id": "Arsène" },
]

personas = [ 
    {"id": 1, "name": "Orpheus", "arcana": "Fool", "level": 1, "image": "persona1.png", "in_pool": True, "special": False},
    {"id": 2, "name": "Izanagi", "arcana": "Fool", "level": 1, "image": "persona2.png", "in_pool": True, "special": False},
    {"id": 3, "name": "Arsène", "arcana": "Fool", "level": 1, "image": "persona3.png", "in_pool": True, "special": False},
    {"id": 4, "name": "Slime", "arcana": "Fool", "level": 12, "image": "persona4.png", "in_pool": True, "special": False},
    {"id": 5, "name": "Legion", "arcana": "Fool", "level": 26, "image": "persona5.png", "in_pool": True, "special": False},
    {"id": 6, "name": "Black Frost", "arcana": "Fool", "level": 37, "image": "persona6.png", "in_pool": True, "special": False},
    {"id": 7, "name": "Ose", "arcana": "Fool", "level": 41, "image": "persona7.png", "in_pool": True, "special": False},
    {"id": 8, "name": "Decarabia", "arcana": "Fool", "level": 54, "image": "persona8.png", "in_pool": True, "special": False},
    {"id": 9, "name": "Loki", "arcana": "Fool", "level": 69, "image": "persona9.png", "in_pool": True, "special": False},
    {"id": 10, "name": "Susanoo", "arcana": "Fool", "level": 77, "image": "persona10.png", "in_pool": True, "special": False},
    {"id": 11, "name": "Hermes", "arcana": "Magician", "level": 1, "image": "persona11.png", "in_pool": True, "special": False},
    {"id": 12, "name": "Nekomata", "arcana": "Magician", "level": 3, "image": "persona12.png", "in_pool": True, "special": False},
    {"id": 13, "name": "Jiraiya", "arcana": "Magician", "level": 4, "image": "persona13.png", "in_pool": True, "special": False},
    {"id": 14, "name": "Jack Frost", "arcana": "Magician", "level": 8, "image": "persona14.png", "in_pool": True, "special": False},
    {"id": 15, "name": "Pyro Jack", "arcana": "Magician", "level": 15, "image": "persona15.png", "in_pool": True, "special": False},
    {"id": 16, "name": "Hua Po", "arcana": "Magician", "level": 19, "image": "persona16.png", "in_pool": True, "special": False},
    {"id": 17, "name": "Zorro", "arcana": "Magician", "level": 22, "image": "persona17.png", "in_pool": True, "special": False},
    {"id": 18, "name": "Sati", "arcana": "Magician", "level": 29, "image": "persona18.png", "in_pool": True, "special": False},
    {"id": 19, "name": "Orobas", "arcana": "Magician", "level": 39, "image": "persona19.png", "in_pool": True, "special": False},
    {"id": 20, "name": "Mercurius", "arcana": "Magician", "level": 43, "image": "persona20.png", "in_pool": True, "special": False},
    {"id": 21, "name": "Rangda", "arcana": "Magician", "level": 50, "image": "persona21.png", "in_pool": True, "special": False},
    {"id": 22, "name": "Surt", "arcana": "Magician", "level": 60, "image": "persona22.png", "in_pool": True, "special": False},
    {"id": 23, "name": "Futsunushi", "arcana": "Magician", "level": 74, "image": "persona23.png", "in_pool": True, "special": False},
    {"id": 24, "name": "Apsaras", "arcana": "Priestess", "level": 2, "image": "persona24.png", "in_pool": True, "special": False},
    {"id": 25, "name": "Unicorn", "arcana": "Priestess", "level": 11, "image": "persona25.png", "in_pool": True, "special": False},
    {"id": 26, "name": "Konohana Sakuya", "arcana": "Priestess", "level": 15, "image": "persona26.png", "in_pool": True, "special": False},
    {"id": 27, "name": "Lucia", "arcana": "Priestess", "level": 18, "image": "persona27.png", "in_pool": True, "special": False},
    {"id": 28, "name": "High Pixie", "arcana": "Priestess", "level": 20, "image": "persona28.png", "in_pool": True, "special": False},
    {"id": 29, "name": "Johanna", "arcana": "Priestess", "level": 28, "image": "persona29.png", "in_pool": True, "special": False},
    {"id": 30, "name": "Sarasvati", "arcana": "Priestess", "level": 32, "image": "persona30.png", "in_pool": True, "special": False},
    {"id": 31, "name": "Ganga", "arcana": "Priestess", "level": 41, "image": "persona31.png", "in_pool": True, "special": False},
    {"id": 32, "name": "Parvati", "arcana": "Priestess", "level": 48, "image": "persona32.png", "in_pool": True, "special": False},
    {"id": 33, "name": "Kikuri-Hime", "arcana": "Priestess", "level": 53, "image": "persona33.png", "in_pool": True, "special": False},
    {"id": 34, "name": "Scathach", "arcana": "Priestess", "level": 75, "image": "persona34.png", "in_pool": True, "special": False},
    {"id": 35, "name": "Penthesilea", "arcana": "Empress", "level": 20, "image": "persona35.png", "in_pool": True, "special": False},
    {"id": 36, "name": "Leanan Sidhe", "arcana": "Empress", "level": 21, "image": "persona36.png", "in_pool": True, "special": False},
    {"id": 37, "name": "Yakshini", "arcana": "Empress", "level": 32, "image": "persona37.png", "in_pool": True, "special": False},
    {"id": 38, "name": "Milady", "arcana": "Empress", "level": 36, "image": "persona38.png", "in_pool": True, "special": False},
    {"id": 39, "name": "Hariti", "arcana": "Empress", "level": 48, "image": "persona39.png", "in_pool": True, "special": False},
    {"id": 40, "name": "Gabriel", "arcana": "Empress", "level": 62, "image": "persona40.png", "in_pool": True, "special": False},
    {"id": 41, "name": "Skadi", "arcana": "Empress", "level": 68, "image": "persona41.png", "in_pool": True, "special": False},
    {"id": 42, "name": "Mother Harlot", "arcana": "Empress", "level": 77, "image": "persona42.png", "in_pool": True, "special": False},
    {"id": 43, "name": "Alilat", "arcana": "Empress", "level": 84, "image": "persona43.png", "in_pool": True, "special": False},
    {"id": 44, "name": "Forneus", "arcana": "Emperor", "level": 7, "image": "persona44.png", "in_pool": True, "special": False},
    {"id": 45, "name": "Polydeuces", "arcana": "Emperor", "level": 14, "image": "persona45.png", "in_pool": True, "special": False},
    {"id": 46, "name": "Oberon", "arcana": "Emperor", "level": 16, "image": "persona46.png", "in_pool": True, "special": False},
    {"id": 47, "name": "Take-Mikazuchi", "arcana": "Emperor", "level": 23, "image": "persona47.png", "in_pool": True, "special": False},
    {"id": 48, "name": "Goemon", "arcana": "Emperor", "level": 27, "image": "persona48.png", "in_pool": True, "special": False},
    {"id": 49, "name": "King Frost", "arcana": "Emperor", "level": 34, "image": "persona49.png", "in_pool": True, "special": False},
    {"id": 50, "name": "Naga Raja", "arcana": "Emperor", "level": 43, "image": "persona50.png", "in_pool": True, "special": False},
    {"id": 51, "name": "Belphegor", "arcana": "Emperor", "level": 53, "image": "persona51.png", "in_pool": True, "special": False},
    {"id": 52, "name": "Barong", "arcana": "Emperor", "level": 63, "image": "persona52.png", "in_pool": True, "special": False},
    {"id": 53, "name": "Odin", "arcana": "Emperor", "level": 74, "image": "persona53.png", "in_pool": True, "special": False},
    {"id": 54, "name": "Omoikane", "arcana": "Hierophant", "level": 7, "image": "persona54.png", "in_pool": True, "special": False},
    {"id": 55, "name": "Berith", "arcana": "Hierophant", "level": 13, "image": "persona55.png", "in_pool": True, "special": False},
    {"id": 56, "name": "Shiisaa", "arcana": "Hierophant", "level": 23, "image": "persona56.png", "in_pool": True, "special": False},
    {"id": 57, "name": "Psyche", "arcana": "Hierophant", "level": 25, "image": "persona57.png", "in_pool": True, "special": False},
    {"id": 58, "name": "Flauros", "arcana": "Hierophant", "level": 33, "image": "persona58.png", "in_pool": True, "special": False},
    {"id": 59, "name": "Castor", "arcana": "Hierophant", "level": 39, "image": "persona59.png", "in_pool": True, "special": False},
    {"id": 60, "name": "Thoth", "arcana": "Hierophant", "level": 40, "image": "persona60.png", "in_pool": True, "special": False},
    {"id": 61, "name": "Hokuto Seikun", "arcana": "Hierophant", "level": 47, "image": "persona61.png", "in_pool": True, "special": False},
    {"id": 62, "name": "Daisoujou", "arcana": "Hierophant", "level": 59, "image": "persona62.png", "in_pool": True, "special": False},
    {"id": 63, "name": "Kohryu", "arcana": "Hierophant", "level": 71, "image": "persona63.png", "in_pool": True, "special": False},
    {"id": 64, "name": "Io", "arcana": "Lovers", "level": 1, "image": "persona64.png", "in_pool": True, "special": False},
    {"id": 65, "name": "Pixie", "arcana": "Lovers", "level": 2, "image": "persona65.png", "in_pool": True, "special": False},
    {"id": 66, "name": "Silky", "arcana": "Lovers", "level": 5, "image": "persona66.png", "in_pool": True, "special": False},
    {"id": 67, "name": "Tam Lin", "arcana": "Lovers", "level": 13, "image": "persona67.png", "in_pool": True, "special": False},
    {"id": 68, "name": "Carmen", "arcana": "Lovers", "level": 19, "image": "persona68.png", "in_pool": True, "special": False},
    {"id": 69, "name": "Narcissus", "arcana": "Lovers", "level": 23, "image": "persona69.png", "in_pool": True, "special": False},
    {"id": 70, "name": "Queen Medb", "arcana": "Lovers", "level": 28, "image": "persona70.png", "in_pool": True, "special": False},
    {"id": 71, "name": "Himiko", "arcana": "Lovers", "level": 34, "image": "persona71.png", "in_pool": True, "special": False},
    {"id": 72, "name": "Saki Mitama", "arcana": "Lovers", "level": 36, "image": "persona72.png", "in_pool": True, "special": False},
    {"id": 73, "name": "Titania", "arcana": "Lovers", "level": 49, "image": "persona73.png", "in_pool": True, "special": False},
    {"id": 74, "name": "Raphael", "arcana": "Lovers", "level": 60, "image": "persona74.png", "in_pool": True, "special": False},
    {"id": 75, "name": "Cybele", "arcana": "Lovers", "level": 67, "image": "persona75.png", "in_pool": True, "special": False},
    {"id": 76, "name": "Ara Mitama", "arcana": "Chariot", "level": 6, "image": "persona76.png", "in_pool": True, "special": False},
    {"id": 77, "name": "Tomoe", "arcana": "Chariot", "level": 6, "image": "persona77.png", "in_pool": True, "special": False},
    {"id": 78, "name": "Chimera", "arcana": "Chariot", "level": 9, "image": "persona78.png", "in_pool": True, "special": False},
    {"id": 79, "name": "Zouchouten", "arcana": "Chariot", "level": 14, "image": "persona79.png", "in_pool": True, "special": False},
    {"id": 80, "name": "Captain Kidd", "arcana": "Chariot", "level": 18, "image": "persona80.png", "in_pool": True, "special": False},
    {"id": 81, "name": "Mithras", "arcana": "Chariot", "level": 24, "image": "persona81.png", "in_pool": True, "special": False},
    {"id": 82, "name": "Palladion", "arcana": "Chariot", "level": 27, "image": "persona82.png", "in_pool": True, "special": False},
    {"id": 83, "name": "Oni", "arcana": "Chariot", "level": 31, "image": "persona83.png", "in_pool": True, "special": False},
    {"id": 84, "name": "Shiki-Ouji", "arcana": "Chariot", "level": 45, "image": "persona84.png", "in_pool": True, "special": False},
    {"id": 85, "name": "Koumokuten", "arcana": "Chariot", "level": 52, "image": "persona85.png", "in_pool": True, "special": False},
    {"id": 86, "name": "Thor", "arcana": "Chariot", "level": 64, "image": "persona86.png", "in_pool": True, "special": False},
    {"id": 87, "name": "Angel", "arcana": "Justice", "level": 4, "image": "persona87.png", "in_pool": True, "special": False},
    {"id": 88, "name": "Archangel", "arcana": "Justice", "level": 10, "image": "persona88.png", "in_pool": True, "special": False},
    {"id": 89, "name": "Principality", "arcana": "Justice", "level": 16, "image": "persona89.png", "in_pool": True, "special": False},
    {"id": 90, "name": "Power", "arcana": "Justice", "level": 25, "image": "persona90.png", "in_pool": True, "special": False},
    {"id": 91, "name": "Virtue", "arcana": "Justice", "level": 32, "image": "persona91.png", "in_pool": True, "special": False},
    {"id": 92, "name": "Robin Hood", "arcana": "Justice", "level": 37, "image": "persona92.png", "in_pool": True, "special": False},
    {"id": 93, "name": "Nemesis", "arcana": "Justice", "level": 37, "image": "persona93.png", "in_pool": True, "special": False},
    {"id": 94, "name": "Dominion", "arcana": "Justice", "level": 42, "image": "persona94.png", "in_pool": True, "special": False},
    {"id": 95, "name": "Throne", "arcana": "Justice", "level": 52, "image": "persona95.png", "in_pool": True, "special": False},
    {"id": 96, "name": "Melchizedek", "arcana": "Justice", "level": 66, "image": "persona96.png", "in_pool": True, "special": False},
    {"id": 97, "name": "Onmoraki", "arcana": "Hermit", "level": 8, "image": "persona97.png", "in_pool": True, "special": False},
    {"id": 98, "name": "Naga", "arcana": "Hermit", "level": 17, "image": "persona98.png", "in_pool": True, "special": False},
    {"id": 99, "name": "Lamia", "arcana": "Hermit", "level": 25, "image": "persona99.png", "in_pool": True, "special": False},
    {"id": 100, "name": "Mothman", "arcana": "Hermit", "level": 31, "image": "persona100.png", "in_pool": True, "special": False},
    {"id": 101, "name": "Dakini", "arcana": "Hermit", "level": 38, "image": "persona101.png", "in_pool": True, "special": False},
    {"id": 102, "name": "Kurama Tengu", "arcana": "Hermit", "level": 46, "image": "persona102.png", "in_pool": True, "special": False},
    {"id": 103, "name": "Nebiros", "arcana": "Hermit", "level": 52, "image": "persona103.png", "in_pool": True, "special": False},
    {"id": 104, "name": "Kumbhanda", "arcana": "Hermit", "level": 61, "image": "persona104.png", "in_pool": True, "special": False},
    {"id": 105, "name": "Arahabaki", "arcana": "Hermit", "level": 68, "image": "persona105.png", "in_pool": True, "special": False},
    {"id": 106, "name": "Fortuna", "arcana": "Fortune", "level": 15, "image": "persona106.png", "in_pool": True, "special": False},
    {"id": 107, "name": "Sandman", "arcana": "Fortune", "level": 20, "image": "persona107.png", "in_pool": True, "special": False},
    {"id": 108, "name": "Kusi Mitama", "arcana": "Fortune", "level": 28, "image": "persona108.png", "in_pool": True, "special": False},
    {"id": 109, "name": "Clotho", "arcana": "Fortune", "level": 37, "image": "persona109.png", "in_pool": True, "special": False},
    {"id": 110, "name": "Lachesis", "arcana": "Fortune", "level": 44, "image": "persona110.png", "in_pool": True, "special": False},
    {"id": 111, "name": "Sukuna-Hikona", "arcana": "Fortune", "level": 55, "image": "persona111.png", "in_pool": True, "special": False},
    {"id": 112, "name": "Atropos", "arcana": "Fortune", "level": 56, "image": "persona112.png", "in_pool": True, "special": False},
    {"id": 113, "name": "Norn", "arcana": "Fortune", "level": 65, "image": "persona113.png", "in_pool": True, "special": False},
    {"id": 114, "name": "Lakshmi", "arcana": "Fortune", "level": 73, "image": "persona114.png", "in_pool": True, "special": False},
    {"id": 115, "name": "Valkyrie", "arcana": "Strength", "level": 10, "image": "persona115.png", "in_pool": True, "special": False},
    {"id": 116, "name": "Rakshasa", "arcana": "Strength", "level": 15, "image": "persona116.png", "in_pool": True, "special": False},
    {"id": 117, "name": "Matador", "arcana": "Strength", "level": 22, "image": "persona117.png", "in_pool": True, "special": False},
    {"id": 118, "name": "Jikokuten", "arcana": "Strength", "level": 29, "image": "persona118.png", "in_pool": True, "special": False},
    {"id": 119, "name": "Cerberus", "arcana": "Strength", "level": 35, "image": "persona119.png", "in_pool": True, "special": False},
    {"id": 120, "name": "Hanuman", "arcana": "Strength", "level": 36, "image": "persona120.png", "in_pool": True, "special": False},
    {"id": 121, "name": "White Rider", "arcana": "Strength", "level": 46, "image": "persona121.png", "in_pool": True, "special": False},
    {"id": 122, "name": "Siegfried", "arcana": "Strength", "level": 54, "image": "persona122.png", "in_pool": True, "special": False},
    {"id": 123, "name": "Kali", "arcana": "Strength", "level": 63, "image": "persona123.png", "in_pool": True, "special": False},
    {"id": 124, "name": "Atavaka", "arcana": "Strength", "level": 72, "image": "persona124.png", "in_pool": True, "special": False},
    {"id": 125, "name": "Inugami", "arcana": "Hanged Man", "level": 10, "image": "persona125.png", "in_pool": True, "special": False},
    {"id": 126, "name": "Take-Minakata", "arcana": "Hanged Man", "level": 20, "image": "persona126.png", "in_pool": True, "special": False},
    {"id": 127, "name": "Orthrus", "arcana": "Hanged Man", "level": 27, "image": "persona127.png", "in_pool": True, "special": False},
    {"id": 128, "name": "Vasuki", "arcana": "Hanged Man", "level": 38, "image": "persona128.png", "in_pool": True, "special": False},
    {"id": 129, "name": "Hecatoncheires", "arcana": "Hanged Man", "level": 47, "image": "persona129.png", "in_pool": True, "special": False},
    {"id": 130, "name": "Mada", "arcana": "Hanged Man", "level": 57, "image": "persona130.png", "in_pool": True, "special": False},
    {"id": 131, "name": "Hell Biker", "arcana": "Hanged Man", "level": 65, "image": "persona131.png", "in_pool": True, "special": False},
    {"id": 132, "name": "Attis", "arcana": "Hanged Man", "level": 73, "image": "persona132.png", "in_pool": True, "special": False},
    {"id": 133, "name": "Pisaca", "arcana": "Death", "level": 15, "image": "persona133.png", "in_pool": True, "special": False},
    {"id": 134, "name": "Pale Rider", "arcana": "Death", "level": 23, "image": "persona134.png", "in_pool": True, "special": False},
    {"id": 135, "name": "Loa", "arcana": "Death", "level": 33, "image": "persona135.png", "in_pool": True, "special": False},
    {"id": 136, "name": "Samael", "arcana": "Death", "level": 41, "image": "persona136.png", "in_pool": True, "special": False},
    {"id": 137, "name": "Mot", "arcana": "Death", "level": 58, "image": "persona137.png", "in_pool": True, "special": False},
    {"id": 138, "name": "Alice", "arcana": "Death", "level": 68, "image": "persona138.png", "in_pool": True, "special": False},
    {"id": 139, "name": "Nigi Mitama", "arcana": "Temperance", "level": 12, "image": "persona139.png", "in_pool": True, "special": False},
    {"id": 140, "name": "Mitra", "arcana": "Temperance", "level": 22, "image": "persona140.png", "in_pool": True, "special": False},
    {"id": 141, "name": "Genbu", "arcana": "Temperance", "level": 30, "image": "persona141.png", "in_pool": True, "special": False},
    {"id": 142, "name": "Seiryu", "arcana": "Temperance", "level": 38, "image": "persona142.png", "in_pool": True, "special": False},
    {"id": 143, "name": "Okuninushi", "arcana": "Temperance", "level": 44, "image": "persona143.png", "in_pool": True, "special": False},
    {"id": 144, "name": "Suzaku", "arcana": "Temperance", "level": 55, "image": "persona144.png", "in_pool": True, "special": False},
    {"id": 145, "name": "Byakko", "arcana": "Temperance", "level": 63, "image": "persona145.png", "in_pool": True, "special": False},
    {"id": 146, "name": "Yurlungur", "arcana": "Temperance", "level": 71, "image": "persona146.png", "in_pool": True, "special": False},
    {"id": 147, "name": "Lilim", "arcana": "Devil", "level": 8, "image": "persona147.png", "in_pool": True, "special": False},
    {"id": 148, "name": "Mokoi", "arcana": "Devil", "level": 18, "image": "persona148.png", "in_pool": True, "special": False},
    {"id": 149, "name": "Baphomet", "arcana": "Devil", "level": 30, "image": "persona149.png", "in_pool": True, "special": False},
    {"id": 150, "name": "Incubus", "arcana": "Devil", "level": 37, "image": "persona150.png", "in_pool": True, "special": False},
    {"id": 151, "name": "Succubus", "arcana": "Devil", "level": 47, "image": "persona151.png", "in_pool": True, "special": False},
    {"id": 152, "name": "Pazuzu", "arcana": "Devil", "level": 56, "image": "persona152.png", "in_pool": True, "special": False},
    {"id": 153, "name": "Lilith", "arcana": "Devil", "level": 65, "image": "persona153.png", "in_pool": True, "special": False},
    {"id": 154, "name": "Abaddon", "arcana": "Devil", "level": 76, "image": "persona154.png", "in_pool": True, "special": False},
    {"id": 155, "name": "Beelzebub", "arcana": "Devil", "level": 81, "image": "persona155.png", "in_pool": True, "special": True},
    {"id": 156, "name": "Eligor", "arcana": "Tower", "level": 31, "image": "persona156.png", "in_pool": True, "special": False},
    {"id": 157, "name": "Cu Chulainn", "arcana": "Tower", "level": 40, "image": "persona157.png", "in_pool": True, "special": False},
    {"id": 158, "name": "Bishamonten", "arcana": "Tower", "level": 60, "image": "persona158.png", "in_pool": True, "special": False},
    {"id": 159, "name": "Qitian Dasheng", "arcana": "Tower", "level": 67, "image": "persona159.png", "in_pool": True, "special": False},
    {"id": 160, "name": "Masakado", "arcana": "Tower", "level": 79, "image": "persona160.png", "in_pool": True, "special": False},
    {"id": 161, "name": "Shiva", "arcana": "Tower", "level": 82, "image": "persona161.png", "in_pool": True, "special": False},
    {"id": 162, "name": "Chi You", "arcana": "Tower", "level": 86, "image": "persona162.png", "in_pool": True, "special": False},
    {"id": 163, "name": "Neko Shogun", "arcana": "Star", "level": 17, "image": "persona163.png", "in_pool": True, "special": True},
    {"id": 164, "name": "Setanta", "arcana": "Star", "level": 29, "image": "persona164.png", "in_pool": True, "special": False},
    {"id": 165, "name": "Kintoki-Douji", "arcana": "Star", "level": 35, "image": "persona165.png", "in_pool": True, "special": False},
    {"id": 166, "name": "Cendrillon", "arcana": "Star", "level": 36, "image": "persona166.png", "in_pool": True, "special": False},
    {"id": 167, "name": "Kaiwan", "arcana": "Star", "level": 42, "image": "persona167.png", "in_pool": True, "special": False},
    {"id": 168, "name": "Ganesha", "arcana": "Star", "level": 51, "image": "persona168.png", "in_pool": True, "special": False},
    {"id": 169, "name": "Vanadis", "arcana": "Star", "level": 58, "image": "persona169.png", "in_pool": True, "special": False},
    {"id": 170, "name": "Garuda", "arcana": "Star", "level": 64, "image": "persona170.png", "in_pool": True, "special": False},
    {"id": 171, "name": "Houou", "arcana": "Star", "level": 70, "image": "persona171.png", "in_pool": True, "special": False},
    {"id": 172, "name": "Saturnus", "arcana": "Star", "level": 76, "image": "persona172.png", "in_pool": True, "special": False},
    {"id": 173, "name": "Helel", "arcana": "Star", "level": 88, "image": "persona173.png", "in_pool": True, "special": False},
    {"id": 174, "name": "Gurulu", "arcana": "Moon", "level": 14, "image": "persona174.png", "in_pool": True, "special": False},
    {"id": 175, "name": "Yamata-no-Orochi", "arcana": "Moon", "level": 25, "image": "persona175.png", "in_pool": True, "special": False},
    {"id": 176, "name": "Kaguya", "arcana": "Moon", "level": 34, "image": "persona176.png", "in_pool": True, "special": False},
    {"id": 177, "name": "Girimekhala", "arcana": "Moon", "level": 39, "image": "persona177.png", "in_pool": True, "special": False},
    {"id": 178, "name": "Dionysus", "arcana": "Moon", "level": 49, "image": "persona178.png", "in_pool": True, "special": False},
    {"id": 179, "name": "Chernobog", "arcana": "Moon", "level": 56, "image": "persona179.png", "in_pool": True, "special": False},
    {"id": 180, "name": "Seth", "arcana": "Moon", "level": 62, "image": "persona180.png", "in_pool": True, "special": False},
    {"id": 181, "name": "Baal Zebul", "arcana": "Moon", "level": 72, "image": "persona181.png", "in_pool": True, "special": False},
    {"id": 182, "name": "Sandalphon", "arcana": "Moon", "level": 80, "image": "persona182.png", "in_pool": True, "special": False},
    {"id": 183, "name": "Yatagarasu", "arcana": "Sun", "level": 24, "image": "persona183.png", "in_pool": True, "special": False},
    {"id": 184, "name": "Thunderbird", "arcana": "Sun", "level": 35, "image": "persona184.png", "in_pool": True, "special": False},
    {"id": 185, "name": "Quetzalcoatl", "arcana": "Sun", "level": 45, "image": "persona185.png", "in_pool": True, "special": False},
    {"id": 186, "name": "Jatayu", "arcana": "Sun", "level": 55, "image": "persona186.png", "in_pool": True, "special": False},
    {"id": 187, "name": "Horus", "arcana": "Sun", "level": 67, "image": "persona187.png", "in_pool": True, "special": False},
    {"id": 188, "name": "Vishnu", "arcana": "Sun", "level": 78, "image": "persona188.png", "in_pool": True, "special": False},
    {"id": 189, "name": "Asura", "arcana": "Sun", "level": 85, "image": "persona189.png", "in_pool": True, "special": False},
    {"id": 190, "name": "Anubis", "arcana": "Judgement", "level": 40, "image": "persona190.png", "in_pool": True, "special": False},
    {"id": 191, "name": "Trumpeter", "arcana": "Judgement", "level": 59, "image": "persona191.png", "in_pool": True, "special": False},
    {"id": 192, "name": "Michael", "arcana": "Judgement", "level": 70, "image": "persona192.png", "in_pool": True, "special": False},
    {"id": 193, "name": "Satan", "arcana": "Judgement", "level": 82, "image": "persona193.png", "in_pool": True, "special": False},
    {"id": 194, "name": "Nidhoggr", "arcana": "Aeon", "level": 47, "image": "persona194.png", "in_pool": True, "special": False},
    {"id": 195, "name": "Uriel", "arcana": "Aeon", "level": 57, "image": "persona195.png", "in_pool": True, "special": False},
    {"id": 196, "name": "Ananta", "arcana": "Aeon", "level": 73, "image": "persona196.png", "in_pool": True, "special": False},
    {"id": 197, "name": "Metatron", "arcana": "Aeon", "level": 87, "image": "persona197.png", "in_pool": True, "special": False},
    {"id": 198, "name": "Lucifer", "arcana": "Judgement", "level": 89, "image": "persona198.png", "in_pool": False, "special": True},
    {"id": 199, "name": "Thanatos", "arcana": "Death", "level": 80, "image": "persona199.png", "in_pool": False, "special": True},
    {"id": 200, "name": "Messiah", "arcana": "Judgement", "level": 91, "image": "persona200.png", "in_pool": False, "special": True},
    {"id": 201, "name": "Magatsu-Izanagi", "arcana": "Tower", "level": 80, "image": "persona201.png", "in_pool": False, "special": True},
    {"id": 202, "name": "Izanagi-no-Okami", "arcana": "World", "level": 91, "image": "persona202.png", "in_pool": False, "special": True},
    {"id": 203, "name": "Satanael", "arcana": "Fool", "level": 80, "image": "persona203.png", "in_pool": False, "special": True},
    {"id": 204, "name": "Raoul", "arcana": "Fool", "level": 91, "image": "persona204.png", "in_pool": False, "special": True},
  ]

specials_dict = {
        "Makoto Yuki": {
            "Lucifer": {
                "Samael": True, 
                "Abaddon": True,
                "Beelzebub": True,
                "Satan": True,
                "Helel": True,
            },
           "Thanatos":{
                "Pale Rider": True,
                "Loa": True,
                "Samael": True,
                "Mot": True,
                "Alice": True,
           },
           "Messiah":{
               "Orpheus": True,
               "Thanatos": True,
           }
        },
          "Yu Narukami": {
              "Lucifer": {
                "Samael": True, 
                "Abaddon": True,
                "Beelzebub": True,
                "Satan": True,
                "Helel": True,
            },
            "Magatsu-Izanagi":{
                 "Yamata-no-Orochi": True,
                 "Throne": True,
                 "Naga Raja": True,
                 "Barong": True,
                 "Norn": True,
            },
            "Izanagi-no-Okami": {
                "Izanagi": True,
                "Magatsu-Izanagi": True,
            }
          },
          "Ren Amamiya": {
              "Lucifer": {
                "Samael": True, 
                "Abaddon": True,
                "Beelzebub": True, 
                "Satan": True,
                "Helel": True,
              },
              "Satanael":{
                  "Legion": True, 
                  "Mercurius": True,
                  "Michael": True,
                  "Succubus": True,
                  "Satan": True,
                },
                "Raoul": {
                    "Arsène": True,
                    "Satanael": True,
                }
              }  
                  
    }          





    

    
    



