arcanas = [
    {"id": 1, "name": "Fool"},
    {"id": 2, "name": "Magician"},
    {"id": 3, "name": "Priestess"},
    {"id": 4, "name": "Empress"},
    {"id": 5, "name": "Emperor"},
    {"id": 6, "name": "Hierophant"},
    {"id": 7, "name": "Lovers"},
    {"id": 8, "name": "Chariot"},
    {"id": 9, "name": "Justice"},
    {"id": 10, "name": "Hermit"},
    {"id": 11, "name": "Fortune"},
    {"id": 12, "name": "Strength"},
    {"id": 13, "name": "Hanged Man"},
    {"id": 14, "name": "Death"},
    {"id": 15, "name": "Temperance"},
    {"id": 16, "name": "Devil"},
    {"id": 17, "name": "Tower"},
    {"id": 18, "name": "Star"},
    {"id": 19, "name": "Moon"},
    {"id": 20, "name": "Sun"},
    {"id": 21, "name": "Judgement"},
    {"id": 22, "name": "Aeon"}
]

wildcards = [
    {"id": 1, "name": "Makoto Yuki", "image": "makoto_yuki_wildcard.png", "initial_persona_id": 1},
    {"id": 2, "name": "Yu Narukami", "image": "yu_narukami_wildcard.png", "initial_persona_id": 2},
    {"id": 3, "name": "Ren Amamiya", "image": "ren_amamiya_wildcard.png", "initial_persona_id": 3}
]

personas = [
    {"id": 1, "name": "Orpheus", "arcana_id": 1, "level": 1, "image": "persona1.png", "in_pool": True, "special": False},
    {"id": 2, "name": "Izanagi", "arcana_id": 1, "level": 1, "image": "persona2.png", "in_pool": True, "special": False},
    {"id": 3, "name": "Arsène", "arcana_id": 1, "level": 1, "image": "persona3.png", "in_pool": True, "special": False},
    {"id": 4, "name": "Slime", "arcana_id": 1, "level": 12, "image": "persona4.png", "in_pool": True, "special": False},
    {"id": 5, "name": "Legion", "arcana_id": 1, "level": 26, "image": "persona5.png", "in_pool": True, "special": False},
    {"id": 6, "name": "Black Frost", "arcana_id": 1, "level": 37, "image": "persona6.png", "in_pool": True, "special": False},
    {"id": 7, "name": "Ose", "arcana_id": 1, "level": 41, "image": "persona7.png", "in_pool": True, "special": False},
    {"id": 8, "name": "Decarabia", "arcana_id": 1, "level": 54, "image": "persona8.png", "in_pool": True, "special": False},
    {"id": 9, "name": "Loki", "arcana_id": 1, "level": 69, "image": "persona9.png", "in_pool": True, "special": False},
    {"id": 10, "name": "Susanoo", "arcana_id": 1, "level": 77, "image": "persona10.png", "in_pool": True, "special": False},
    {"id": 11, "name": "Hermes", "arcana_id": 2, "level": 1, "image": "persona11.png", "in_pool": True, "special": False},
    {"id": 12, "name": "Nekomata", "arcana_id": 2, "level": 3, "image": "persona12.png", "in_pool": True, "special": False},
    {"id": 13, "name": "Jiraiya", "arcana_id": 2, "level": 4, "image": "persona13.png", "in_pool": True, "special": False},
    {"id": 14, "name": "Jack Frost", "arcana_id": 2, "level": 8, "image": "persona14.png", "in_pool": True, "special": False},
    {"id": 15, "name": "Pyro Jack", "arcana_id": 2, "level": 15, "image": "persona15.png", "in_pool": True, "special": False},
    {"id": 16, "name": "Hua Po", "arcana_id": 2, "level": 19, "image": "persona16.png", "in_pool": True, "special": False},
    {"id": 17, "name": "Zorro", "arcana_id": 2, "level": 22, "image": "persona17.png", "in_pool": True, "special": False},
    {"id": 18, "name": "Sati", "arcana_id": 2, "level": 29, "image": "persona18.png", "in_pool": True, "special": False},
    {"id": 19, "name": "Orobas", "arcana_id": 2, "level": 39, "image": "persona19.png", "in_pool": True, "special": False},
    {"id": 20, "name": "Mercurius", "arcana_id": 2, "level": 43, "image": "persona20.png", "in_pool": True, "special": False},
    {"id": 21, "name": "Rangda", "arcana_id": 2, "level": 50, "image": "persona21.png", "in_pool": True, "special": False},
    {"id": 22, "name": "Surt", "arcana_id": 2, "level": 60, "image": "persona22.png", "in_pool": True, "special": False},
    {"id": 23, "name": "Futsunushi", "arcana_id": 2, "level": 74, "image": "persona23.png", "in_pool": True, "special": False},
    {"id": 24, "name": "Apsaras", "arcana_id": 3, "level": 2, "image": "persona24.png", "in_pool": True, "special": False},
    {"id": 25, "name": "Unicorn", "arcana_id": 3, "level": 11, "image": "persona25.png", "in_pool": True, "special": False},
    {"id": 26, "name": "Konohana Sakuya", "arcana_id": 3, "level": 15, "image": "persona26.png", "in_pool": True, "special": False},
    {"id": 27, "name": "Lucia", "arcana_id": 3, "level": 18, "image": "persona27.png", "in_pool": True, "special": False},
    {"id": 28, "name": "High Pixie", "arcana_id": 3, "level": 20, "image": "persona28.png", "in_pool": True, "special": False},
    {"id": 29, "name": "Johanna", "arcana_id": 3, "level": 28, "image": "persona29.png", "in_pool": True, "special": False},
    {"id": 30, "name": "Sarasvati", "arcana_id": 3, "level": 32, "image": "persona30.png", "in_pool": True, "special": False},
    {"id": 31, "name": "Ganga", "arcana_id": 3, "level": 41, "image": "persona31.png", "in_pool": True, "special": False},
    {"id": 32, "name": "Parvati", "arcana_id": 3, "level": 48, "image": "persona32.png", "in_pool": True, "special": False},
    {"id": 33, "name": "Kikuri-Hime", "arcana_id": 3, "level": 53, "image": "persona33.png", "in_pool": True, "special": False},
    {"id": 34, "name": "Scathach", "arcana_id": 3, "level": 75, "image": "persona34.png", "in_pool": True, "special": False},
    {"id": 35, "name": "Penthesilea", "arcana_id": 4, "level": 20, "image": "persona35.png", "in_pool": True, "special": False},
    {"id": 36, "name": "Leanan Sidhe", "arcana_id": 4, "level": 21, "image": "persona36.png", "in_pool": True, "special": False},
    {"id": 37, "name": "Yakshini", "arcana_id": 4, "level": 32, "image": "persona37.png", "in_pool": True, "special": False},
    {"id": 38, "name": "Milady", "arcana_id": 4, "level": 36, "image": "persona38.png", "in_pool": True, "special": False},
    {"id": 39, "name": "Hariti", "arcana_id": 4, "level": 48, "image": "persona39.png", "in_pool": True, "special": False},
    {"id": 40, "name": "Gabriel", "arcana_id": 4, "level": 62, "image": "persona40.png", "in_pool": True, "special": False},
    {"id": 41, "name": "Skadi", "arcana_id": 4, "level": 68, "image": "persona41.png", "in_pool": True, "special": False},
    {"id": 42, "name": "Mother Harlot", "arcana_id": 4, "level": 77, "image": "persona42.png", "in_pool": True, "special": False},
    {"id": 43, "name": "Alilat", "arcana_id": 4, "level": 84, "image": "persona43.png", "in_pool": True, "special": False},
    {"id": 44, "name": "Forneus", "arcana_id": 5, "level": 7, "image": "persona44.png", "in_pool": True, "special": False},
    {"id": 45, "name": "Polydeuces", "arcana_id": 5, "level": 14, "image": "persona45.png", "in_pool": True, "special": False},
    {"id": 46, "name": "Oberon", "arcana_id": 5, "level": 16, "image": "persona46.png", "in_pool": True, "special": False},
    {"id": 47, "name": "Take-Mikazuchi", "arcana_id": 5, "level": 23, "image": "persona47.png", "in_pool": True, "special": False},
    {"id": 48, "name": "Goemon", "arcana_id": 5, "level": 27, "image": "persona48.png", "in_pool": True, "special": False},
    {"id": 49, "name": "King Frost", "arcana_id": 5, "level": 34, "image": "persona49.png", "in_pool": True, "special": False},
    {"id": 50, "name": "Naga Raja", "arcana_id": 5, "level": 43, "image": "persona50.png", "in_pool": True, "special": False},
    {"id": 51, "name": "Belphegor", "arcana_id": 5, "level": 53, "image": "persona51.png", "in_pool": True, "special": False},
    {"id": 52, "name": "Barong", "arcana_id": 5, "level": 63, "image": "persona52.png", "in_pool": True, "special": False},
    {"id": 53, "name": "Odin", "arcana_id": 5, "level": 74, "image": "persona53.png", "in_pool": True, "special": False},
    {"id": 54, "name": "Omoikane", "arcana_id": 6, "level": 7, "image": "persona54.png", "in_pool": True, "special": False},
    {"id": 55, "name": "Berith", "arcana_id": 6, "level": 13, "image": "persona55.png", "in_pool": True, "special": False},
    {"id": 56, "name": "Shiisaa", "arcana_id": 6, "level": 23, "image": "persona56.png", "in_pool": True, "special": False},
    {"id": 57, "name": "Psyche", "arcana_id": 6, "level": 25, "image": "persona57.png", "in_pool": True, "special": False},
    {"id": 58, "name": "Flauros", "arcana_id": 6, "level": 33, "image": "persona58.png", "in_pool": True, "special": False},
    {"id": 59, "name": "Castor", "arcana_id": 6, "level": 39, "image": "persona59.png", "in_pool": True, "special": False},
    {"id": 60, "name": "Thoth", "arcana_id": 6, "level": 40, "image": "persona60.png", "in_pool": True, "special": False},
    {"id": 61, "name": "Hokuto Seikun", "arcana_id": 6, "level": 47, "image": "persona61.png", "in_pool": True, "special": False},
    {"id": 62, "name": "Daisoujou", "arcana_id": 6, "level": 59, "image": "persona62.png", "in_pool": True, "special": False},
    {"id": 63, "name": "Kohryu", "arcana_id": 6, "level": 71, "image": "persona63.png", "in_pool": True, "special": False},
    {"id": 64, "name": "Io", "arcana_id": 7, "level": 1, "image": "persona64.png", "in_pool": True, "special": False},
    {"id": 65, "name": "Pixie", "arcana_id": 7, "level": 2, "image": "persona65.png", "in_pool": True, "special": False},
    {"id": 66, "name": "Silky", "arcana_id": 7, "level": 5, "image": "persona66.png", "in_pool": True, "special": False},
    {"id": 67, "name": "Tam Lin", "arcana_id": 7, "level": 13, "image": "persona67.png", "in_pool": True, "special": False},
    {"id": 68, "name": "Carmen", "arcana_id": 7, "level": 19, "image": "persona68.png", "in_pool": True, "special": False},
    {"id": 69, "name": "Narcissus", "arcana_id": 7, "level": 23, "image": "persona69.png", "in_pool": True, "special": False},
    {"id": 70, "name": "Queen Medb", "arcana_id": 7, "level": 28, "image": "persona70.png", "in_pool": True, "special": False},
    {"id": 71, "name": "Himiko", "arcana_id": 7, "level": 34, "image": "persona71.png", "in_pool": True, "special": False},
    {"id": 72, "name": "Saki Mitama", "arcana_id": 7, "level": 36, "image": "persona72.png", "in_pool": True, "special": False},
    {"id": 73, "name": "Titania", "arcana_id": 7, "level": 49, "image": "persona73.png", "in_pool": True, "special": False},
    {"id": 74, "name": "Raphael", "arcana_id": 7, "level": 60, "image": "persona74.png", "in_pool": True, "special": False},
    {"id": 75, "name": "Cybele", "arcana_id": 7, "level": 67, "image": "persona75.png", "in_pool": True, "special": False},
    {"id": 76, "name": "Ara Mitama", "arcana_id": 8, "level": 6, "image": "persona76.png", "in_pool": True, "special": False},
    {"id": 77, "name": "Tomoe", "arcana_id": 8, "level": 6, "image": "persona77.png", "in_pool": True, "special": False},
    {"id": 78, "name": "Chimera", "arcana_id": 8, "level": 9, "image": "persona78.png", "in_pool": True, "special": False},
    {"id": 79, "name": "Zouchouten", "arcana_id": 8, "level": 14, "image": "persona79.png", "in_pool": True, "special": False},
    {"id": 80, "name": "Captain Kidd", "arcana_id": 8, "level": 18, "image": "persona80.png", "in_pool": True, "special": False},
    {"id": 81, "name": "Mithras", "arcana_id": 8, "level": 24, "image": "persona81.png", "in_pool": True, "special": False},
    {"id": 82, "name": "Palladion", "arcana_id": 8, "level": 27, "image": "persona82.png", "in_pool": True, "special": False},
    {"id": 83, "name": "Oni", "arcana_id": 8, "level": 31, "image": "persona83.png", "in_pool": True, "special": False},
    {"id": 84, "name": "Shiki-Ouji", "arcana_id": 8, "level": 45, "image": "persona84.png", "in_pool": True, "special": False},
    {"id": 85, "name": "Koumokuten", "arcana_id": 8, "level": 52, "image": "persona85.png", "in_pool": True, "special": False},
    {"id": 86, "name": "Thor", "arcana_id": 8, "level": 64, "image": "persona86.png", "in_pool": True, "special": False},
    {"id": 87, "name": "Angel", "arcana_id": 9, "level": 4, "image": "persona87.png", "in_pool": True, "special": False},
    {"id": 88, "name": "Archangel", "arcana_id": 9, "level": 10, "image": "persona88.png", "in_pool": True, "special": False},
    {"id": 89, "name": "Principality", "arcana_id": 9, "level": 16, "image": "persona89.png", "in_pool": True, "special": False},
    {"id": 90, "name": "Power", "arcana_id": 9, "level": 25, "image": "persona90.png", "in_pool": True, "special": False},
    {"id": 91, "name": "Virtue", "arcana_id": 9, "level": 32, "image": "persona91.png", "in_pool": True, "special": False},
    {"id": 92, "name": "Robin Hood", "arcana_id": 9, "level": 37, "image": "persona92.png", "in_pool": True, "special": False},
    {"id": 93, "name": "Nemesis", "arcana_id": 9, "level": 37, "image": "persona93.png", "in_pool": True, "special": False},
    {"id": 94, "name": "Dominion", "arcana_id": 9, "level": 42, "image": "persona94.png", "in_pool": True, "special": False},
    {"id": 95, "name": "Throne", "arcana_id": 9, "level": 52, "image": "persona95.png", "in_pool": True, "special": False},
    {"id": 96, "name": "Melchizedek", "arcana_id": 9, "level": 66, "image": "persona96.png", "in_pool": True, "special": False},
    {"id": 97, "name": "Onmoraki", "arcana_id": 10, "level": 8, "image": "persona97.png", "in_pool": True, "special": False},
    {"id": 98, "name": "Naga", "arcana_id": 10, "level": 17, "image": "persona98.png", "in_pool": True, "special": False},
    {"id": 99, "name": "Lamia", "arcana_id": 10, "level": 25, "image": "persona99.png", "in_pool": True, "special": False},
    {"id": 100, "name": "Mothman", "arcana_id": 10, "level": 31, "image": "persona100.png", "in_pool": True, "special": False},
    {"id": 101, "name": "Dakini", "arcana_id": 10, "level": 38, "image": "persona101.png", "in_pool": True, "special": False},
    {"id": 102, "name": "Kurama Tengu", "arcana_id": 10, "level": 46, "image": "persona102.png", "in_pool": True, "special": False},
    {"id": 103, "name": "Nebiros", "arcana_id": 10, "level": 52, "image": "persona103.png", "in_pool": True, "special": False},
    {"id": 104, "name": "Kumbhanda", "arcana_id": 10, "level": 61, "image": "persona104.png", "in_pool": True, "special": False},
    {"id": 105, "name": "Arahabaki", "arcana_id": 10, "level": 68, "image": "persona105.png", "in_pool": True, "special": False},
    {"id": 106, "name": "Fortuna", "arcana_id": 11, "level": 15, "image": "persona106.png", "in_pool": True, "special": False},
    {"id": 107, "name": "Sandman", "arcana_id": 11, "level": 20, "image": "persona107.png", "in_pool": True, "special": False},
    {"id": 108, "name": "Kusi Mitama", "arcana_id": 11, "level": 28, "image": "persona108.png", "in_pool": True, "special": False},
    {"id": 109, "name": "Clotho", "arcana_id": 11, "level": 37, "image": "persona109.png", "in_pool": True, "special": False},
    {"id": 110, "name": "Lachesis", "arcana_id": 11, "level": 44, "image": "persona110.png", "in_pool": True, "special": False},
    {"id": 111, "name": "Sukuna-Hikona", "arcana_id": 11, "level": 55, "image": "persona111.png", "in_pool": True, "special": False},
    {"id": 112, "name": "Atropos", "arcana_id": 11, "level": 56, "image": "persona112.png", "in_pool": True, "special": False},
    {"id": 113, "name": "Norn", "arcana_id": 11, "level": 65, "image": "persona113.png", "in_pool": True, "special": False},
    {"id": 114, "name": "Lakshmi", "arcana_id": 11, "level": 73, "image": "persona114.png", "in_pool": True, "special": False},


    

    
    



]