arcana_map = {
   "fool":{
       "fool": "fool",
       "magician": "hierophant",
       "priestess": "magician",
       "empress": "star",
       "emperor": "temperance",
       "hierophant": "hanged man",
       "lovers": "justice",
       "chariot": "emperor",
       "justice": "lovers",
       "hermit": "priestess",
       "fortune": "strength",
       "strength": "death",
       "hanged man": "devil",
       "death": "fortune",
       "temperance": "chariot",
       "devil": "hermit",
       "tower": "moon",
       "star": "devil",
       "moon": "empress",
       "sun": "judgement",
       "judgement": "aeon",
       "aeon": "death"
   },
    "magician":{
       "fool": "hierophant",
       "magician": "magician",
       "priestess": "justice",
       "empress": "hanged man",
       "emperor": "lovers",
       "hierophant": "hermit",
       "lovers": "chariot",
       "chariot": "devil",
       "justice": "hierophant",
       "hermit": "moon",
       "fortune": "lovers",
       "strength": "emperor",
       "hanged man": "fool",
       "death": "preistess",
       "temperance": "justice",
       "devil": "temperance",
       "tower": "chariot",
       "star": "strength",
       "moon": "strength",
       "sun": "empress",
       "judgement": "star",
       "aeon": "sun"
    },
     "priestess":{
       "fool": "magician",
       "magician": "justice",
       "priestess": "priestess",
       "empress": "temperance",
       "emperor": "justice",
       "hierophant": "lovers",
       "lovers": "magician",
       "chariot": "fool",
       "justice": "lovers",
       "hermit": "strength",
       "fortune": "hanged man",
       "strength": "moon",
       "hanged man": "hierophant",
       "death": "justice",
       "temperance": "fortune",
       "devil": "emperor",
       "tower": "empress",
       "star": "emperor",
       "moon": "star",
       "sun": "hierophant",
       "judgement": "hanged man",
       "aeon": "empress"
     },
     "empress":{
       "fool": "star",
       "magician": "hanged man",
       "priestess": "temperance",
       "empress": "empress",
       "emperor": "chariot",
       "hierophant": "tower",
       "lovers": "moon",
       "chariot": "hermit",
       "justice": "emperor",
       "hermit": "sun",
       "fortune": "strength",
       "strength": "fool",
       "hanged man": "star",
       "death": "lovers",
       "temperance": "hierophant",
       "devil": "tower",
       "tower": "devil",
       "star": "priestess",
       "moon": "aeon",
       "sun": "emperor",
       "judgement": "lovers",
       "aeon": "priestess"
     },
     "emperor":{
      "fool": "temperance",
       "magician": "lovers",
       "priestess": "justice",
       "empress": "chariot",
       "emperor": "emperor",
       "hierophant": "strength",
       "lovers": "chariot",
       "chariot": "devil",
       "justice": "hanged man",
       "hermit": "hierophant",
       "fortune": "star",
       "strength": "magician",
       "hanged man": "death",
       "death": "hermit",
       "temperance": "star",
       "devil": "moon",
       "tower": "strength",
       "star": "hierophant",
       "moon": "lovers",
       "sun": "temperance",
       "judgement": "sun",
       "aeon": "fortune"
   },
    "hierophant":{
       "fool": "hanged man",
       "magician": "hermit",
       "priestess": "lovers",
       "empress": "tower",
       "emperor": "strength",
       "hierophant": "hierophant",
       "lovers": "magician",
       "chariot": "justice",
       "justice": "fool",
       "hermit": "chariot",
       "fortune": "moon",
       "strength": "fortune",
       "hanged man": "strength",
       "death": "fortune",
       "temperance": "hermit",
       "devil": "priestess",
       "tower": "temperance",
       "star": "moon",
       "moon": "magician",
       "sun": "tower",
       "judgement": "emperor",
       "aeon": "sun"
   },
   "lovers":{
       "fool": "justice",
       "magician": "chariot",
       "priestess": "magician",
       "empress": "moon",
       "emperor": "chariot",
       "hierophant": "magician",
       "lovers": "lovers",
       "chariot": "priestess",
       "justice": "emperor",
       "hermit": "fool",
       "fortune": "temperance",
       "strength": "hermit",
       "hanged man": "justice",
       "death": "hanged man",
       "temperance": "death",
       "devil": "star",
       "tower": "sun",
       "star": "death",
       "moon": "empress",
       "sun": "devil",
       "judgement": "moon",
       "aeon": "tower"
   },
   "chariot":{
       "fool": "emperor",
       "magician": "devil",
       "priestess": "fool",
       "empress": "hermit",
       "emperor": "devil",
       "hierophant": "justice",
       "lovers": "priestess",
       "chariot": "chariot",
       "justice": "magician",
       "hermit": "lovers",
       "fortune": "priestess",
       "strength": "temperance",
       "hanged man": "strength",
       "death": "hierophant",
       "temperance": "hermit",
       "devil": "hanged man",
       "tower": "star",
       "star": "fortune",
       "moon": "temperance",
       "sun": "strength",
       "judgement": "empress",
       "aeon": "hermit"
   },
   "justice":{
       "fool": "lovers",
       "magician": "hierophant",
       "priestess": "lovers",
       "empress": "emperor",
       "emperor": "hanged man",
       "hierophant": "fool",
       "lovers": "emperor",
       "chariot": "magician",
       "justice": "justice",
       "hermit": "magician",
       "fortune": "hanged man",
       "strength": "star",
       "hanged man": "priestess",
       "death": "hermit",
       "temperance": "moon",
       "devil": "temperance",
       "tower": "sun",
       "star": "hermit",
       "moon": "temperance",
       "sun": "magician",
       "judgement": "fool",
       "aeon": "judgement"
   },
   "hermit":{
       "fool": "priestess",
       "magician": "moon",
       "priestess": "strength",
       "empress": "sun",
       "emperor": "hierophant",
       "hierophant": "chariot",
       "lovers": "fool",
       "chariot": "lovers",
       "justice": "magician",
       "hermit": "hermit",
       "fortune": "justice",
       "strength": "emperor",
       "hanged man": "temperance",
       "death": "chariot",
       "temperance": "magician",
       "devil": "strength",
       "tower": "emperor",
       "star": "fool",
       "moon": "hierophant",
       "sun": "star",
       "judgement": "temperance",
       "aeon": "devil"
   },
   "fortune":{
      "fool": "strength",
       "magician": "lovers",
       "priestess": "hanged man",
       "empress": "strength",
       "emperor": "star",
       "hierophant": "moon",
       "lovers": "temperance",
       "chariot": "priestess",
       "justice": "hanged man",
       "hermit": "justice",
       "fortune": "fortune",
       "strength": "sun",
       "hanged man": "magician",
       "death": "star",
       "temperance": "tower",
       "devil": "empress",
       "tower": "aeon",
       "star": "magician",
       "moon": "death",
       "sun": "judgement",
       "judgement": "sun",
       "aeon": "moon"
   },
   "strength":{
       "fool": "death",
       "magician": "emperor",
       "priestess": "moon",
       "empress": "fool",
       "emperor": "magician",
       "hierophant": "fortune",
       "lovers": "hermit",
       "chariot": "temperance",
       "justice": "star",
       "hermit": "emperor",
       "fortune": "sun",
       "strength": "strength",
       "hanged man": "chariot",
       "death": "empress",
       "temperance": "moon",
       "devil": "lovers",
       "tower": "hanged man",
       "star": "priestess",
       "moon": "devil",
       "sun": "lovers",
       "judgement": "devil",
       "aeon": "fool"
   },
    "hanged man":{
       "fool": "devil",
       "magician": "fool",
       "priestess": "hierophant",
       "empress": "star",
       "emperor": "death",
       "hierophant": "strength",
       "lovers": "justice",
       "chariot": "strength",
       "justice": "priestess",
       "hermit": "temperance",
       "fortune": "magician",
       "strength": "chariot",
       "hanged man": "hanged man",
       "death": "strength",
       "temperance": "hierophant",
       "devil": "priestess",
       "tower": "death",
       "star": "empress",
       "moon": "chariot",
       "sun": "aeon",
       "judgement": "tower",
       "aeon": "death"
    },
    "death":{
       "fool": "fortune",
       "magician": "priestess",
       "priestess": "justice",
       "empress": "lovers",
       "emperor": "hermit",
       "hierophant": "fortune",
       "lovers": "hanged man",
       "chariot": "hierophant",
       "justice": "hermit",
       "hermit": "chariot",
       "fortune": "star",
       "strength": "empress",
       "hanged man": "strength",
       "death": "death",
       "temperance": "devil",
       "devil": "tower",
       "tower": "aeon",
       "star": "sun",
       "moon": "hanged man",
       "sun": "justice",
       "judgement": "devil",
       "aeon": ""
    },
    "temperance":{
       "fool": "chariot",
       "magician": "justice",
       "priestess": "fortune",
       "empress": "hierophant",
       "emperor": "star",
       "hierophant": "hermit",
       "lovers": "death",
       "chariot": "hermit",
       "justice": "moon",
       "hermit": "magician",
       "fortune": "tower",
       "strength": "moon",
       "hanged man": "hierophant",
       "death": "devil",
       "temperance": "temperance",
       "devil": "fool",
       "tower": "devil",
       "star": "fortune",
       "moon": "priestess",
       "sun": "chariot",
       "judgement": "empress",
       "aeon": "justice"
    },
    "devil":{
       "fool": "hermit",
       "magician": "temperance",
       "priestess": "emperor",
       "empress": "tower",
       "emperor": "moon",
       "hierophant": "priestess",
       "lovers": "star",
       "chariot": "hanged man",
       "justice": "temperance",
       "hermit": "strength",
       "fortune": "empress",
       "strength": "lovers",
       "hanged man": "priestess",
       "death": "tower",
       "temperance": "fool",
       "devil": "devil",
       "tower": "judgement",
       "star": "justice",
       "moon": "fool",
       "sun": "death",
       "judgement": "death",
       "aeon": "star"
    },
    "tower":{
       "fool": "moon",
       "magician": "chariot",
       "priestess": "empress",
       "empress": "devil",
       "emperor": "strength",
       "hierophant": "temperance",
       "lovers": "sun",
       "chariot": "star",
       "justice": "sun",
       "hermit": "emperor",
       "fortune": "aeon",
       "strength": "hanged man",
       "hanged man": "death",
       "death": "aeon",
       "temperance": "devil",
       "devil": "judgement",
       "tower": "tower",
       "star": "judgement",
       "moon": "fortune",
       "sun": "hierophant",
       "judgement": "aeon",
       "aeon": "sun"
    },
    "star":{
       "fool": "devil",
       "magician": "strength",
       "priestess": "emperor",
       "empress": "priestess",
       "emperor": "hierophant",
       "hierophant": "moon",
       "lovers": "death",
       "chariot": "fortune",
       "justice": "hermit",
       "hermit": "fool",
       "fortune": "magician",
       "strength": "priestess",
       "hanged man": "empress",
       "death": "sun",
       "temperance": "fortune",
       "devil": "justice",
       "tower": "judgement",
       "star": "star",
       "moon": "sun",
       "sun": "justice",
       "judgement": "tower",
       "aeon": "judgement"
    },
    "moon":{
       "fool": "empress",
       "magician": "strength",
       "priestess": "star",
       "empress": "aeon",
       "emperor": "lovers",
       "hierophant": "magician",
       "lovers": "empress",
       "chariot": "temperance",
       "justice": "temperance",
       "hermit": "hierophant",
       "fortune": "death",
       "strength": "devil",
       "hanged man": "chariot",
       "death": "hanged man",
       "temperance": "priestess",
       "devil": "fool",
       "tower": "fortune",
       "star": "sun",
       "moon": "moon",
       "sun": "tower",
       "judgement": "fortune",
       "aeon": "judgement"
    },
    "sun":{
       "fool": "judgement",
       "magician": "empress",
       "priestess": "hierophant",
       "empress": "emperor",
       "emperor": "temperance",
       "hierophant": "tower",
       "lovers": "devil",
       "chariot": "strength",
       "justice": "magician",
       "hermit": "star",
       "fortune": "judgement",
       "strength": "lovers",
       "hanged man": "aeon",
       "death": "justice",
       "temperance": "chariot",
       "devil": "death",
       "tower": "hierophant",
       "star": "justice",
       "moon": "tower",
       "sun": "sun",
       "judgement": "aeon",
       "aeon": "empress"
    },
    "judgement":{
       "fool": "aeon",
       "magician": "star",
       "priestess": "hanged man",
       "empress": "lovers",
       "emperor": "sun",
       "hierophant": "emperor",
       "lovers": "moon",
       "chariot": "empress",
       "justice": "fool",
       "hermit": "temperance",
       "fortune": "sun",
       "strength": "devil",
       "hanged man": "tower",
       "death": "devil",
       "temperance": "empress",
       "devil": "death",
       "tower": "aeon",
       "star": "tower",
       "moon": "fortune",
       "sun": "aeon",
       "judgement": "judgement",
       "aeon": "fool"
    },
    "aeon":{
       "fool": "death",
       "magician": "sun",
       "priestess": "empress",
       "empress": "priestess",
       "emperor": "fortune",
       "hierophant": "sun",
       "lovers": "tower",
       "chariot": "hermit",
       "justice": "judgement",
       "hermit": "devil",
       "fortune": "moon",
       "strength": "fool",
       "hanged man": "death",
       "death": "",
       "temperance": "justice",
       "devil": "star",
       "tower": "sun",
       "star": "judgement",
       "moon": "judgement",
       "sun": "empress",
       "judgement": "fool",
       "aeon": "aeon"
    }
}