arcana_map = {
   "Fool":{
       "Fool": "Fool",
       "Magician": "Hierophant",
       "Priestess": "Magician",
       "Empress": "Star",
       "Emperor": "Temperance",
       "Hierophant": "Hanged Man",
       "Lovers": "Justice",
       "Chariot": "Emperor",
       "Justice": "Lovers",
       "Hermit": "Priestess",
       "Fortune": "Strength",
       "Strength": "Death",
       "Hanged Man": "Devil",
       "Death": "Fortune",
       "Temperance": "Chariot",
       "Devil": "Hermit",
       "Tower": "Moon",
       "Star": "Devil",
       "Moon": "Empress",
       "Sun": "Judgement",
       "Judgement": "Aeon",
       "Aeon": "Death"
   },
    "Magician":{
       "Fool": "Hierophant",
       "Magician": "Magician",
       "Priestess": "Justice",
       "Empress": "Hanged Man",
       "Emperor": "Lovers",
       "Hierophant": "Hermit",
       "Lovers": "Chariot",
       "Chariot": "Devil",
       "Justice": "Hierophant",
       "Hermit": "Moon",
       "Fortune": "Lovers",
       "Strength": "Emperor",
       "Hanged Man": "Fool",
       "Death": "Preistess",
       "Temperance": "Justice",
       "Devil": "Temperance",
       "Tower": "Chariot",
       "Star": "Strength",
       "Moon": "Strength",
       "Sun": "Empress",
       "Judgement": "Star",
       "Aeon": "Sun"
    },
     "Priestess":{
       "Fool": "Magician",
       "Magician": "Justice",
       "Priestess": "Priestess",
       "Empress": "Temperance",
       "Emperor": "Justice",
       "Hierophant": "Lovers",
       "Lovers": "Magician",
       "Chariot": "Fool",
       "Justice": "Lovers",
       "Hermit": "Strength",
       "Fortune": "Hanged Man",
       "Strength": "Moon",
       "Hanged Man": "Hierophant",
       "Death": "Justice",
       "Temperance": "Fortune",
       "Devil": "Emperor",
       "Tower": "Empress",
       "Star": "Emperor",
       "Moon": "Star",
       "Sun": "Hierophant",
       "Judgement": "Hanged Man",
       "Aeon": "Empress"
     },
     "Empress":{
       "Fool": "Star",
       "Magician": "Hanged Man",
       "Priestess": "Temperance",
       "Empress": "Empress",
       "Emperor": "Chariot",
       "Hierophant": "Tower",
       "Lovers": "Moon",
       "Chariot": "Hermit",
       "Justice": "Emperor",
       "Hermit": "Sun",
       "Fortune": "Strength",
       "Strength": "Fool",
       "Hanged Man": "Star",
       "Death": "Lovers",
       "Temperance": "Hierophant",
       "Devil": "Tower",
       "Tower": "Devil",
       "Star": "Priestess",
       "Moon": "Aeon",
       "Sun": "Emperor",
       "Judgement": "Lovers",
       "Aeon": "Priestess"
     },
     "Emperor":{
      "Fool": "Temperance",
       "Magician": "Lovers",
       "Priestess": "Justice",
       "Empress": "Chariot",
       "Emperor": "Emperor",
       "Hierophant": "Strength",
       "Lovers": "Chariot",
       "Chariot": "Devil",
       "Justice": "Hanged Man",
       "Hermit": "Hierophant",
       "Fortune": "Star",
       "Strength": "Magician",
       "Hanged Man": "Death",
       "Death": "Hermit",
       "Temperance": "Star",
       "Devil": "Moon",
       "Tower": "Strength",
       "Star": "Hierophant",
       "Moon": "Lovers",
       "Sun": "Temperance",
       "Judgement": "Sun",
       "Aeon": "Fortune"
   },
    "Hierophant":{
       "Fool": "Hanged Man",
       "Magician": "Hermit",
       "Priestess": "Lovers",
       "Empress": "Tower",
       "Emperor": "Strength",
       "Hierophant": "Hierophant",
       "Lovers": "Magician",
       "Chariot": "Justice",
       "Justice": "Fool",
       "Hermit": "Chariot",
       "Fortune": "Moon",
       "Strength": "Fortune",
       "Hanged Man": "Strength",
       "Death": "Fortune",
       "Temperance": "Hermit",
       "Devil": "Priestess",
       "Tower": "Temperance",
       "Star": "Moon",
       "Moon": "Magician",
       "Sun": "Tower",
       "Judgement": "Emperor",
       "Aeon": "Sun"
   },
   "Lovers":{
       "Fool": "Justice",
       "Magician": "Chariot",
       "Priestess": "Magician",
       "Empress": "Moon",
       "Emperor": "Chariot",
       "Hierophant": "Magician",
       "Lovers": "Lovers",
       "Chariot": "Priestess",
       "Justice": "Emperor",
       "Hermit": "Fool",
       "Fortune": "Temperance",
       "Strength": "Hermit",
       "Hanged Man": "Justice",
       "Death": "Hanged Man",
       "Temperance": "Death",
       "Devil": "Star",
       "Tower": "Sun",
       "Star": "Death",
       "Moon": "Empress",
       "Sun": "Devil",
       "Judgement": "Moon",
       "Aeon": "Tower"
   },
   "Chariot":{
       "Fool": "Emperor",
       "Magician": "Devil",
       "Priestess": "Fool",
       "Empress": "Hermit",
       "Emperor": "Devil",
       "Hierophant": "Justice",
       "Lovers": "Priestess",
       "Chariot": "Chariot",
       "Justice": "Magician",
       "Hermit": "Lovers",
       "Fortune": "Priestess",
       "Strength": "Temperance",
       "Hanged Man": "Strength",
       "Death": "Hierophant",
       "Temperance": "Hermit",
       "Devil": "Hanged Man",
       "Tower": "Star",
       "Star": "Fortune",
       "Moon": "Temperance",
       "Sun": "Strength",
       "Judgement": "Empress",
       "Aeon": "Hermit"
   },
   "Justice":{
       "Fool": "Lovers",
       "Magician": "Hierophant",
       "Priestess": "Lovers",
       "Empress": "Emperor",
       "Emperor": "Hanged Man",
       "Hierophant": "Fool",
       "Lovers": "Emperor",
       "Chariot": "Magician",
       "Justice": "Justice",
       "Hermit": "Magician",
       "Fortune": "Hanged Man",
       "Strength": "Star",
       "Hanged Man": "Priestess",
       "Death": "Hermit",
       "Temperance": "Moon",
       "Devil": "Temperance",
       "Tower": "Sun",
       "Star": "Hermit",
       "Moon": "Temperance",
       "Sun": "Magician",
       "Judgement": "Fool",
       "Aeon": "Judgement"
   },
   "Hermit":{
       "Fool": "Priestess",
       "Magician": "Moon",
       "Priestess": "Strength",
       "Empress": "Sun",
       "Emperor": "Hierophant",
       "Hierophant": "Chariot",
       "Lovers": "Fool",
       "Chariot": "Lovers",
       "Justice": "Magician",
       "Hermit": "Hermit",
       "Fortune": "Justice",
       "Strength": "Emperor",
       "Hanged Man": "Temperance",
       "Death": "Chariot",
       "Temperance": "Magician",
       "Devil": "Strength",
       "Tower": "Emperor",
       "Star": "Fool",
       "Moon": "Hierophant",
       "Sun": "Star",
       "Judgement": "Temperance",
       "Aeon": "Devil"
   },
   "Fortune":{
      "Fool": "Strength",
       "Magician": "Lovers",
       "Priestess": "Hanged Man",
       "Empress": "Strength",
       "Emperor": "Star",
       "Hierophant": "Moon",
       "Lovers": "Temperance",
       "Chariot": "Priestess",
       "Justice": "Hanged Man",
       "Hermit": "Justice",
       "Fortune": "Fortune",
       "Strength": "Sun",
       "Hanged Man": "Magician",
       "Death": "Star",
       "Temperance": "Tower",
       "Devil": "Empress",
       "Tower": "Aeon",
       "Star": "Magician",
       "Moon": "Death",
       "Sun": "Judgement",
       "Judgement": "Sun",
       "Aeon": "Moon"
   },
   "Strength":{
       "Fool": "Death",
       "Magician": "Emperor",
       "Priestess": "Moon",
       "Empress": "Fool",
       "Emperor": "Magician",
       "Hierophant": "Fortune",
       "Lovers": "Hermit",
       "Chariot": "Temperance",
       "Justice": "Star",
       "Hermit": "Emperor",
       "Fortune": "Sun",
       "Strength": "Strength",
       "Hanged Man": "Chariot",
       "Death": "Empress",
       "Temperance": "Moon",
       "Devil": "Lovers",
       "Tower": "Hanged Man",
       "Star": "Priestess",
       "Moon": "Devil",
       "Sun": "Lovers",
       "Judgement": "Devil",
       "Aeon": "Fool"
   },
    "Hanged Man":{
       "Fool": "Devil",
       "Magician": "Fool",
       "Priestess": "Hierophant",
       "Empress": "Star",
       "Emperor": "Death",
       "Hierophant": "Strength",
       "Lovers": "Justice",
       "Chariot": "Strength",
       "Justice": "Priestess",
       "Hermit": "Temperance",
       "Fortune": "Magician",
       "Strength": "Chariot",
       "Hanged Man": "Hanged Man",
       "Death": "Strength",
       "Temperance": "Hierophant",
       "Devil": "Priestess",
       "Tower": "Death",
       "Star": "Empress",
       "Moon": "Chariot",
       "Sun": "Aeon",
       "Judgement": "Tower",
       "Aeon": "Death"
    },
    "Death":{
       "Fool": "Fortune",
       "Magician": "Priestess",
       "Priestess": "Justice",
       "Empress": "Lovers",
       "Emperor": "Hermit",
       "Hierophant": "Fortune",
       "Lovers": "Hanged Man",
       "Chariot": "Hierophant",
       "Justice": "Hermit",
       "Hermit": "Chariot",
       "Fortune": "Star",
       "Strength": "Empress",
       "Hanged Man": "Strength",
       "Death": "Death",
       "Temperance": "Devil",
       "Devil": "Tower",
       "Tower": "Aeon",
       "Star": "Sun",
       "Moon": "Hanged Man",
       "Sun": "Justice",
       "Judgement": "Devil",
       "Aeon": "Moon"
    },
    "Temperance":{
       "Fool": "Chariot",
       "Magician": "Justice",
       "Priestess": "Fortune",
       "Empress": "Hierophant",
       "Emperor": "Star",
       "Hierophant": "Hermit",
       "Lovers": "Death",
       "Chariot": "Hermit",
       "Justice": "Moon",
       "Hermit": "Magician",
       "Fortune": "Tower",
       "Strength": "Moon",
       "Hanged Man": "Hierophant",
       "Death": "Devil",
       "Temperance": "Temperance",
       "Devil": "Fool",
       "Tower": "Devil",
       "Star": "Fortune",
       "Moon": "Priestess",
       "Sun": "Chariot",
       "Judgement": "Empress",
       "Aeon": "Justice"
    },
    "Devil":{
       "Fool": "Hermit",
       "Magician": "Temperance",
       "Priestess": "Emperor",
       "Empress": "Tower",
       "Emperor": "Moon",
       "Hierophant": "Priestess",
       "Lovers": "Star",
       "Chariot": "Hanged Man",
       "Justice": "Temperance",
       "Hermit": "Strength",
       "Fortune": "Empress",
       "Strength": "Lovers",
       "Hanged Man": "Priestess",
       "Death": "Tower",
       "Temperance": "Fool",
       "Devil": "Devil",
       "Tower": "Judgement",
       "Star": "Justice",
       "Moon": "Fool",
       "Sun": "Death",
       "Judgement": "Death",
       "Aeon": "Star"
    },
    "Tower":{
       "Fool": "Moon",
       "Magician": "Chariot",
       "Priestess": "Empress",
       "Empress": "Devil",
       "Emperor": "Strength",
       "Hierophant": "Temperance",
       "Lovers": "Sun",
       "Chariot": "Star",
       "Justice": "Sun",
       "Hermit": "Emperor",
       "Fortune": "Aeon",
       "Strength": "Hanged Man",
       "Hanged Man": "Death",
       "Death": "Aeon",
       "Temperance": "Devil",
       "Devil": "Judgement",
       "Tower": "Tower",
       "Star": "Judgement",
       "Moon": "Fortune",
       "Sun": "Hierophant",
       "Judgement": "Aeon",
       "Aeon": "Sun"
    },
    "Star":{
       "Fool": "Devil",
       "Magician": "Strength",
       "Priestess": "Emperor",
       "Empress": "Priestess",
       "Emperor": "Hierophant",
       "Hierophant": "Moon",
       "Lovers": "Death",
       "Chariot": "Fortune",
       "Justice": "Hermit",
       "Hermit": "Fool",
       "Fortune": "Magician",
       "Strength": "Priestess",
       "Hanged Man": "Empress",
       "Death": "Sun",
       "Temperance": "Fortune",
       "Devil": "Justice",
       "Tower": "Judgement",
       "Star": "Star",
       "Moon": "Sun",
       "Sun": "Justice",
       "Judgement": "Tower",
       "Aeon": "Judgement"
    },
    "Moon":{
       "Fool": "Empress",
       "Magician": "Strength",
       "Priestess": "Star",
       "Empress": "Aeon",
       "Emperor": "Lovers",
       "Hierophant": "Magician",
       "Lovers": "Empress",
       "Chariot": "Temperance",
       "Justice": "Temperance",
       "Hermit": "Hierophant",
       "Fortune": "Death",
       "Strength": "Devil",
       "Hanged Man": "Chariot",
       "Death": "Hanged Man",
       "Temperance": "Priestess",
       "Devil": "Fool",
       "Tower": "Fortune",
       "Star": "Sun",
       "Moon": "Moon",
       "Sun": "Tower",
       "Judgement": "Fortune",
       "Aeon": "Judgement"
    },
    "Sun":{
       "Fool": "Judgement",
       "Magician": "Empress",
       "Priestess": "Hierophant",
       "Empress": "Emperor",
       "Emperor": "Temperance",
       "Hierophant": "Tower",
       "Lovers": "Devil",
       "Chariot": "Strength",
       "Justice": "Magician",
       "Hermit": "Star",
       "Fortune": "Judgement",
       "Strength": "Lovers",
       "Hanged Man": "Aeon",
       "Death": "Justice",
       "Temperance": "Chariot",
       "Devil": "Death",
       "Tower": "Hierophant",
       "Star": "Justice",
       "Moon": "Tower",
       "Sun": "Sun",
       "Judgement": "Aeon",
       "Aeon": "Empress"
    },
    "Judgement":{
       "Fool": "Aeon",
       "Magician": "Star",
       "Priestess": "Hanged Man",
       "Empress": "Lovers",
       "Emperor": "Sun",
       "Hierophant": "Emperor",
       "Lovers": "Moon",
       "Chariot": "Empress",
       "Justice": "Fool",
       "Hermit": "Temperance",
       "Fortune": "Sun",
       "Strength": "Devil",
       "Hanged Man": "Tower",
       "Death": "Devil",
       "Temperance": "Empress",
       "Devil": "Death",
       "Tower": "Aeon",
       "Star": "Tower",
       "Moon": "Fortune",
       "Sun": "Aeon",
       "Judgement": "Judgement",
       "Aeon": "Fool"
    },
    "Aeon":{
       "Fool": "Death",
       "Magician": "Sun",
       "Priestess": "Empress",
       "Empress": "Priestess",
       "Emperor": "Fortune",
       "Hierophant": "Sun",
       "Lovers": "Tower",
       "Chariot": "Hermit",
       "Justice": "Judgement",
       "Hermit": "Devil",
       "Fortune": "Moon",
       "Strength": "Fool",
       "Hanged Man": "Death",
       "Death": "Moon",
       "Temperance": "Justice",
       "Devil": "Star",
       "Tower": "Sun",
       "Star": "Judgement",
       "Moon": "Judgement",
       "Sun": "Empress",
       "Judgement": "Fool",
       "Aeon": "Aeon"
    }
}