"""Initial migration

Revision ID: 936820381e57
Revises: 
Create Date: 2025-02-04 23:27:18.423125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '936820381e57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arcanas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('in_pool', sa.Boolean(), nullable=True),
    sa.Column('arcana_id', sa.Integer(), nullable=False),
    sa.Column('special', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.CheckConstraint('level >= 1', name='level_greater_than_zero'),
    sa.ForeignKeyConstraint(['arcana_id'], ['arcanas.id'], name=op.f('fk_personas_arcana_id_arcanas')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('wildcards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('initial_persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['initial_persona_id'], ['personas.id'], name=op.f('fk_wildcards_initial_persona_id_personas')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('wildcard_id', sa.Integer(), nullable=False),
    sa.Column('yen', sa.Integer(), nullable=False),
    sa.Column('stock_limit', sa.Integer(), nullable=True),
    sa.CheckConstraint('level <= 99', name='check_max_level'),
    sa.ForeignKeyConstraint(['wildcard_id'], ['wildcards.id'], name=op.f('fk_players_wildcard_id_wildcards')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('special_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wildcard_id', sa.Integer(), nullable=False),
    sa.Column('special_fusion_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['personas.id'], name=op.f('fk_special_materials_material_id_personas')),
    sa.ForeignKeyConstraint(['special_fusion_id'], ['personas.id'], name=op.f('fk_special_materials_special_fusion_id_personas')),
    sa.ForeignKeyConstraint(['wildcard_id'], ['wildcards.id'], name=op.f('fk_special_materials_wildcard_id_wildcards')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compendiums',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=True),
    sa.CheckConstraint('in_stock IN (0, 1)', name='check_in_stock_boolean'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_compendiums_persona_id_personas')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_compendiums_player_id_players')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], name=op.f('fk_stocks_persona_id_personas')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_stocks_player_id_players')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    op.drop_table('compendiums')
    op.drop_table('special_materials')
    op.drop_table('players')
    op.drop_table('wildcards')
    op.drop_table('personas')
    op.drop_table('arcanas')
    # ### end Alembic commands ###
